services:
  pythonapp:
    build: .
    command: sh -c "sleep 10s; uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - ./:/usr/app/src/
    ports:
      - '0.0.0.0:80:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysqlvol:/var/lib/mysql/
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'Hung0112256'
    ports:
      - '0.0.0.0:3306:3306'

volumes:
  mysqlvol: